# Production environment overrides
version: '3.8'

services:
  sql-server:
    environment:
      - MSSQL_PID=Standard
      - SA_PASSWORD=${SQL_SA_PASSWORD}
    volumes:
      - sql-server-prod-data:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  user-management:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=baseUserManagement;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=true;
      - ConnectionStrings__Redis=redis:6379,password=${REDIS_PASSWORD}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__ExpiryInDays=7
      - Serilog__MinimumLevel=Warning
      - ApplicationInsights__InstrumentationKey=${APP_INSIGHTS_KEY}
    volumes:
      - /var/log/base/user-management:/app/logs
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  api-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Serilog__MinimumLevel=Warning
      - ApplicationInsights__InstrumentationKey=${APP_INSIGHTS_KEY}
    volumes:
      - /var/log/base/api-gateway:/app/logs
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  sql-server-prod-data:
